#! /bin/sh

# This file is part of SXEmacs.

# Copyright (C) 1997  Free Software Foundation, Inc.

# SXEmacs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SXEmacs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ x"$1" = x-q ]
then
    quick=-q
    shift
fi

if [ $# -eq 0 ]
then
    exec gnuclient $quick -batch 
else
# I use "$*" instead of "$@" intentionally -- I don't want to have the
# arguments split.
    exec gnuclient $quick -batch -eval "$*"
fi

